### ISSUE TITLE
USER STORY: text inclusivity checker

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/grob#8]
As a **Site User**, I can **give a text as input on the home page of the website** so that **it shows me the non-inclusive expressions within it that I should consider to replace**.

---
**Acceptance Criteria**
- [x] **Given** that I am linked to the home page of the website, **when** I insert a text in the dedicated input field and click the button underneath, **then** It marks the non-inclusive words within my submitted text.

**Comment by CallumDennisIE** [comment]
Comments from inital PR https://github.com/yannickferenczi/grob/pull/20:

- The user's input is separated into an array of strings.
- The strings are iterated through and the following is checked:
  - Regex is used to check for 'man' at the start and end of each word.
  - Each word is checked to see if it is in an array of family terms ('father', 'mother', etc...)
- If any of the above match, then the output is shown to the user in the DOM

**Comment by CallumDennisIE** [comment]
Dictionary of terms PR https://github.com/yannickferenczi/grob/pull/21:
- A new dictionary has been added that has the non-inclusive terms as the **key** and the inclusive replacement as the **value**

**Comment by CallumDennisIE** [comment]
Term replacement code PR https://github.com/yannickferenczi/grob/pull/24:
- Code will now check through all words inputted by the user. If the term matches a non-inclusive term, then it is replaced by the inclusive term.

**Comment by CallumDennisIE** [comment]
Tooltip code PR https://github.com/yannickferenczi/grob/pull/27:

- Code now uses Materialize Tooltips to show replacement text on hover

https://materializecss.com/tooltips.html

**Comment by CallumDennisIE** [comment]
Improved readability PR https://github.com/yannickferenczi/grob/pull/37:

- Text to be replaced is now highlighted
- The tooltip now provides more info to the user when shown

**Comment by CallumDennisIE** [comment]
Reset Button PR https://github.com/yannickferenczi/grob/pull/39:
- Adds functionality to reset button
- Resets the output when the submit button is clicker - avoids duplication

**Comment by CallumDennisIE** [comment]
Add more replacement terms https://github.com/yannickferenczi/grob/pull/40

**Comment by CallumDennisIE** [comment]
Capitialisation Consistency https://github.com/yannickferenczi/grob/pull/42

Punctuation Consistency https://github.com/yannickferenczi/grob/pull/43

**Comment by CallumDennisIE** [comment]
Fix replacement terms not being highlighted https://github.com/yannickferenczi/grob/pull/44
